version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      # Add any additional environment variables required
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: faizan
      POSTGRES_PASSWORD: faizan
      POSTGRES_DB: postgres
